<Project>
  <Import Project="$(MSBuildThisFileDirectory)eng/Broiler.Packaging.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Debug-Linux;Release-Linux;Debug-Windows;Release-Windows</Configurations>
    <Optimize Condition="$(Configuration.StartsWith('Release'))">true</Optimize>
    <PackageProjectUrl>https://github.com/Broiler-Platform/Broiler.Native</PackageProjectUrl>
    <PackageTags>broiler;native;interop</PackageTags>
  </PropertyGroup>
</Project>
